//
//  DetailsWireframe.swift
//  Pokedex
//
//  Created by Emin on 4.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe<DetailsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(specyURL:URL) {
        let moduleViewController = DetailsViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailsInteractor(requestHandler: RequestHandler())
        let presenter = DetailsPresenter(view: moduleViewController,
                                         interactor: interactor,
                                         wireframe: self,
                                         specyURL: specyURL)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {
}
