//
//  ListInteractor.swift
//  Pokedex
//
//  Created by Emin on 3.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListInteractor {
    
    private var requestHandler: RequestHandling
    
    private var limit : Int
    
    // Limit is set to 50 as default, but it can be change by presenter
    init(requestHandler:RequestHandling, limit: Int = 50) {
        self.requestHandler = requestHandler
        self.limit = limit
    }
}

// MARK: - Extensions -

extension ListInteractor: ListInteractorInterface {
    
    func getSpeciesList(pageNum:Int, _ completion:@escaping ((Result<SpeciesResponse, APIError>) -> Void)) {
        
        let offset = limit * pageNum
        requestHandler.request(route: .getSpeciesList(limit: limit, offset: offset)) { (result:Result<SpeciesResponse, APIError>) in
            completion(result)
        }
        
    }
}
