//
//  ListInterfaces.swift
//  CataPoke
//
//  Created by Emin on 3.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ListWireframeInterface: WireframeInterface {
}

protocol ListViewInterface: ViewInterface {
}

protocol ListPresenterInterface: PresenterInterface {
}

protocol ListInteractorInterface: InteractorInterface {
}
