//
//  ListPresenter.swift
//  CataPoke
//
//  Created by Emin on 3.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListPresenter {

    // MARK: - Private properties -

    private unowned let view: ListViewInterface
    private let interactor: ListInteractorInterface
    private let wireframe: ListWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: ListViewInterface,
        interactor: ListInteractorInterface,
        wireframe: ListWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ListPresenter: ListPresenterInterface {
}
