//
//  ListInterfaces.swift
//  CataPoke
//
//  Created by Emin on 3.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ListWireframeInterface: WireframeInterface {
    func navigateToDetails(specyURL:URL)
}

protocol ListViewInterface: ViewInterface {
    func refreshList()
}

protocol ListPresenterInterface: PresenterInterface {
    func getNewPokemons()
    var numberOfCells: Int {get}
    func cellForRowIndex(index:Int) -> Species
    func didSelectRow(index: Int)
}

protocol ListInteractorInterface: InteractorInterface {
    func getPokemons(pageNum:Int, _ completion:@escaping ((Result<SpeciesResponse, APIError>) -> Void))
}
