//
//  ListWireframe.swift
//  CataPoke
//
//  Created by Emin on 3.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListWireframe: BaseWireframe<ListViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ListViewController()
        super.init(viewController: moduleViewController)

        let interactor = ListInteractor(requestHandler: RequestHandler())
        let presenter = ListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ListWireframe: ListWireframeInterface {
    func navigateToDetails(specyURL: URL) {
        navigationController?.pushWireframe(DetailsWireframe(specyURL: specyURL))
    }
    
}
