//
//  DetailsPresenter.swift
//  CataPoke
//
//  Created by Emin on 4.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: DetailsViewInterface
    private let interactor: DetailsInteractorInterface
    private let wireframe: DetailsWireframeInterface
    
    private let specyURL:URL
    // MARK: - Lifecycle -
    
    init(
        view: DetailsViewInterface,
        interactor: DetailsInteractorInterface,
        wireframe: DetailsWireframeInterface,
        specyURL:URL
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.specyURL = specyURL
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    func viewDidLoad() {
        interactor.getSpecyDetails(url: specyURL) { [weak self] (result:Result<SpeciesDetails,APIError>) in
            guard let self = self else {return}
            
            switch result {
                
            case .success(let response):
                self.fetchEvolutionDetails(specyDetail: response)
                
            case .failure(let rr):
                //TODO: add error popups
                print("Error")
            }
        }
    }
    
    private func fetchEvolutionDetails(specyDetail: SpeciesDetails){
        
        interactor.getEvelolutionChain(url: specyDetail.evolutionChain.url) { [weak self]  (result:Result<EvolutionChainDetails,APIError>) in
            guard let self = self else {return}
            
            switch result {
                
            case .success(let response):

                let model = DetailsViewModel(name: specyDetail.name,
                                             imageURL: self.interactor.getHeaderImageURL(url: self.specyURL))
                self.view.updateUI(model: model)
                
            case .failure(let rr):
                //TODO: add error popups
                print("Error")
            }
        }
    }
    
}
