//
//  DetailsPresenter.swift
//  CataPoke
//
//  Created by Emin on 4.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: DetailsViewInterface
    private let interactor: DetailsInteractorInterface
    private let wireframe: DetailsWireframeInterface
    
    private let specyURL:URL
    // MARK: - Lifecycle -
    
    init(
        view: DetailsViewInterface,
        interactor: DetailsInteractorInterface,
        wireframe: DetailsWireframeInterface,
        specyURL:URL
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.specyURL = specyURL
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    
    
    func viewDidLoad() {
        interactor.getDetails(url: specyURL) { (result:Result<CompleteDetailResponse, APIError>) in
            switch result {
                
            case .success(let response):
                self.view.updateUI(model: response)
                
            case .failure(let rr):
                //TODO: add error popups
                print("Error")
            }
        }
    }
}
