//
//  DetailsInterfaces.swift
//  CataPoke
//
//  Created by Emin on 4.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailsWireframeInterface: WireframeInterface {
}

protocol DetailsViewInterface: ViewInterface {
    func updateUI(model:DetailsViewModel)
}

protocol DetailsPresenterInterface: PresenterInterface {
    func viewDidLoad()
}

protocol DetailsInteractorInterface: InteractorInterface {
    func getSpecyDetails(url:URL, completion:@escaping ((Result<SpeciesDetails, APIError>) -> Void))
    func getEvelolutionChain(url:URL, completion:@escaping ((Result<EvolutionChainDetails, APIError>) -> Void))
    func getHeaderImageURL(url:URL) -> URL?
}

struct DetailsViewModel {
    let name: String
    let imageURL: URL?
    
    //TODO: Add evolution
}
