//
//  DetailsInteractor.swift
//  CataPoke
//
//  Created by Emin on 4.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsInteractor {
    
    private var requestHandler: RequestHandling
    
    init(requestHandler: RequestHandling) {
        self.requestHandler = requestHandler
    }
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {

    
    func getSpecyDetails(url:URL, completion: @escaping ((Result<SpeciesDetails, APIError>) -> Void)) {
            
        requestHandler.request(route: .getSpecies(url)) { (result:Result<SpeciesDetails, APIError>) in
            completion(result)
        }
        
    }
    
    func getEvelolutionChain(url:URL, completion: @escaping ((Result<EvolutionChainDetails, APIError>) -> Void)) {
        requestHandler.request(route: .getEvolutionChain(url)) { (result:Result<EvolutionChainDetails, APIError>) in
            completion(result)
        }
    }
    
    func getHeaderImageURL(url:URL) -> URL? {
        // This is a hacky way to get nice big image from API.
        // Correct way to send another request via 'pokeapi.co/api/v2/pokemon/{pokemonId}/'
        // I don't prefer to send so much request in a single scene, I think api should provide simpler approach.
        let id = StringUtilities.getPokemonIDFromSpeciesResponse(urlStr: url.absoluteString)
        return StringUtilities.getDreamWorldImages(id: id)
    }
    
}
